services:
  notes_app:
    container_name: notes_app
    image: eniek/notes
    network_mode: host
    depends_on:
      - notes_db
    ports:
      - 3000:3000
    environment:
      # The origin of where you will be accessing this website from
      - ORIGIN=http://localhost:3000
      - DB_HOST=localhost
      - DB_PORT=3001
      - DB_DB=notes
      - DB_USER=notes
      - DB_PASSWORD=notesdb1234
  notes_db:
    container_name: notes_db
    image: mysql
    ports:
      - 3001:3306
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=verysecretpassword1234
      - MYSQL_DATABASE=notes
      - MYSQL_USER=notes
      - MYSQL_PASSWORD=notesdb1234
    volumes:
      # Make sure that init.sql is in the same folder as docker-compose.yml
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
